services:
  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 36231:36231
    command: redis-server --loglevel notice --port 36231
    volumes:
      - cache:/data
    networks:
      - backend
      - dokploy-network
  backend:
    image: "steam-backend"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    ports:
      - 3002:3000
    depends_on:
      - cache
    networks:
      - backend
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certResolver=letsencrypt"
      - "traefik.http.routers.backend.rule=Host(`steam.bordas.sk`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
volumes:
  cache:
    driver: local
networks:
  backend:
  dokploy-network:
    external: true
