version: '3'
services:
  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
    - 36231:36231
    command: redis-server --loglevel notice --port 36231
    volumes:
    - cache:/data
    networks:
    - backend
    - dokploy-network
  backend:
    image: 'steam-backend'
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    ports:
    - 3001:3000
    depends_on:
    - cache
    networks:
      - backend
      - dokploy-network
    labels:
      - traefik.enable=true
      - "traefik.http.routers.steambackend.rule=Host(`steam.bordas.sk`) && PathPrefix(`/api`)"
      - traefik.http.routers.backend.entrypoints=web
      - "traefik.http.routers.steambackend.tls.certResolver=letsencrypt"
      - traefik.http.services.steambackend.loadbalancer.server.port=3001
volumes:
  cache:
    driver: local
networks:
  backend:
  dokploy-network:
    external: true