services:
  cache:
    image: redis:7.2.4-alpine
    restart: always
    command: redis-server --loglevel notice --port 36231
    volumes:
      - cache:/data
    networks:
      - steam_bordas_backend
  backend:
    image: ghcr.io/ignissak/steam-friends-fastify:main
    container_name: steam-backend
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    volumes:
      - ./.env:/app/.env
    ports:
      - 3002:3000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP router (for redirect)
      - "traefik.http.routers.steam-backend.entrypoints=http"
      - "traefik.http.routers.steam-backend.rule=Host(`steam.bordas.sk`) && PathPrefix(`/api`)"
      - "traefik.http.routers.steam-backend.middlewares=redirect-to-https"

      # HTTPS router
      - "traefik.http.routers.steam-backend-secure.entrypoints=https"
      - "traefik.http.routers.steam-backend-secure.rule=Host(`steam.bordas.sk`) && PathPrefix(`/api`)"
      - "traefik.http.routers.steam-backend-secure.tls=true"
      - "traefik.http.routers.steam-backend-secure.tls.certresolver=le"
      - "traefik.http.routers.steam-backend-secure.middlewares=sslheader"
      - "traefik.http.routers.steam-backend-secure.service=steam-backend"
      
      - "traefik.http.services.steam-backend.loadbalancer.server.port=3000"
    depends_on:
      - cache
    networks:
      - steam_bordas_backend
      - proxy
    environment:
      - PORT=3000
      - NODE_ENV=production
      - STEAM_AUTH_URL=https://steam.bordas.sk/api/auth/steam
      - STEAM_RETURN_URL=https://steam.bordas.sk/api/auth/steam/return
      - DEBUG=true
      - COOKIE_DOMAIN=steam.bordas.sk
      - REDIRECT_URL=https://steam.bordas.sk/login
      - REDIS_URL="redis://cache:36231"
    secrets:
      - STEAM_API_KEY
      - JWT_SECRET
volumes:
  cache:
    driver: local
networks:
  steam_bordas_backend:
  proxy:
    external: true
secrets:
  STEAM_API_KEY:
    external: true
  JWT_SECRET:
    external: true