version: '3'
services:
  cache:
    image: redis:latest
    restart: always
    ports:
    - 36231:36231
    command: redis-server --loglevel warning --port 36231
    volumes:
    - cache:/data
  backend:
    image: 'steam-backend'
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    ports:
    - 3000:3000
volumes:
  cache:
    driver: local